// Comprehensive language list – all Google Translate supported + Wikipedia extras
// Format: { code, name, nativeName, flag, region, wikiCode }
// wikiCode = Wikipedia subdomain (if different from Google Translate code)

const ALL_LANGUAGES = [

  // ── INDIC / SOUTH ASIAN ────────────────────────────────────────────────────
  {code:"hi",   name:"Hindi",              native:"हिन्दी",          flag:"🇮🇳", region:"Indic"},
  {code:"ne",   name:"Nepali",             native:"नेपाली",           flag:"🇳🇵", region:"Indic"},
  {code:"mr",   name:"Marathi",            native:"मराठी",            flag:"🇮🇳", region:"Indic"},
  {code:"bn",   name:"Bengali",            native:"বাংলা",            flag:"🇧🇩", region:"Indic"},
  {code:"pa",   name:"Punjabi",            native:"ਪੰਜਾਬੀ",           flag:"🇮🇳", region:"Indic"},
  {code:"gu",   name:"Gujarati",           native:"ગુજરાતી",          flag:"🇮🇳", region:"Indic"},
  {code:"or",   name:"Odia",               native:"ଓଡ଼ିଆ",            flag:"🇮🇳", region:"Indic"},
  {code:"as",   name:"Assamese",           native:"অসমীয়া",           flag:"🇮🇳", region:"Indic"},
  {code:"sa",   name:"Sanskrit",           native:"संस्कृतम्",         flag:"🇮🇳", region:"Indic"},
  {code:"mai",  name:"Maithili",           native:"मैथिली",           flag:"🇮🇳", region:"Indic"},
  {code:"bho",  name:"Bhojpuri",           native:"भोजपुरी",          flag:"🇮🇳", region:"Indic"},
  {code:"doi",  name:"Dogri",              native:"डोगरी",             flag:"🇮🇳", region:"Indic"},
  {code:"gom",  name:"Konkani",            native:"कोंकणी",           flag:"🇮🇳", region:"Indic"},
  {code:"sd",   name:"Sindhi",             native:"سنڌي",              flag:"🇵🇰", region:"Indic"},
  {code:"ur",   name:"Urdu",               native:"اردو",              flag:"🇵🇰", region:"Indic"},
  {code:"ks",   name:"Kashmiri",           native:"کٲشُر",            flag:"🇮🇳", region:"Indic", wikiCode:"ks"},
  {code:"mni-Mtei",name:"Meitei (Manipuri)",native:"ꯃꯩꯇꯩ",           flag:"🇮🇳", region:"Indic"},
  {code:"brx",  name:"Bodo",               native:"बड़ो",              flag:"🇮🇳", region:"Indic", wikiCode:"brx", gtFallback:"hi"},
  {code:"sat",  name:"Santali",            native:"ᱥᱟᱱᱛᱟᱲᱤ",         flag:"🇮🇳", region:"Indic", wikiCode:"sat", gtFallback:"bn"},
  {code:"lus",  name:"Mizo",               native:"Mizo tawng",        flag:"🇮🇳", region:"Indic"},
  {code:"raj",  name:"Rajasthani",         native:"राजस्थानी",         flag:"🇮🇳", region:"Indic", wikiCode:"raj", gtFallback:"hi"},
  {code:"anp",  name:"Angika",             native:"अंगिका",            flag:"🇮🇳", region:"Indic", wikiCode:"anp", gtFallback:"hi"},
  {code:"awa",  name:"Awadhi",             native:"अवधी",              flag:"🇮🇳", region:"Indic", wikiCode:"awa", gtFallback:"hi"},
  {code:"hne",  name:"Chhattisgarhi",      native:"छत्तीसगढ़ी",         flag:"🇮🇳", region:"Indic", wikiCode:"hne", gtFallback:"hi"},
  {code:"mag",  name:"Magahi",             native:"मगही",              flag:"🇮🇳", region:"Indic", wikiCode:"mag", gtFallback:"hi"},
  {code:"dty",  name:"Doteli",             native:"डोटेली",            flag:"🇳🇵", region:"Indic", wikiCode:"dty", gtFallback:"ne"},
  {code:"new",  name:"Newar",              native:"नेपाल भाषा",        flag:"🇳🇵", region:"Indic", wikiCode:"new", gtFallback:"ne"},
  {code:"bpy",  name:"Bishnupriya",        native:"বিষ্ণুপ্রিয়া মণিপুরী",flag:"🇮🇳",region:"Indic",wikiCode:"bpy",gtFallback:"bn"},
  {code:"dz",   name:"Dzongkha",           native:"རྫོང་ཁ",            flag:"🇧🇹", region:"Indic", wikiCode:"dz", gtFallback:"ne"},
  {code:"bo",   name:"Tibetan",            native:"བོད་ཡིག",           flag:"🇨🇳", region:"Indic"},
  {code:"si",   name:"Sinhala",            native:"සිංහල",             flag:"🇱🇰", region:"Indic"},

  // ── DRAVIDIAN ──────────────────────────────────────────────────────────────
  {code:"ta",   name:"Tamil",              native:"தமிழ்",             flag:"🇮🇳", region:"Dravidian"},
  {code:"te",   name:"Telugu",             native:"తెలుగు",            flag:"🇮🇳", region:"Dravidian"},
  {code:"kn",   name:"Kannada",            native:"ಕನ್ನಡ",             flag:"🇮🇳", region:"Dravidian"},
  {code:"ml",   name:"Malayalam",          native:"മലയാളം",            flag:"🇮🇳", region:"Dravidian"},
  {code:"tcy",  name:"Tulu",               native:"ತುಳು",              flag:"🇮🇳", region:"Dravidian", wikiCode:"tcy", gtFallback:"kn"},

  // ── CENTRAL ASIAN / TURKIC ─────────────────────────────────────────────────
  {code:"kk",   name:"Kazakh",             native:"Қазақша",           flag:"🇰🇿", region:"Central Asian"},
  {code:"ky",   name:"Kyrgyz",             native:"Кыргызча",          flag:"🇰🇬", region:"Central Asian"},
  {code:"uz",   name:"Uzbek",              native:"Oʻzbek",             flag:"🇺🇿", region:"Central Asian"},
  {code:"tk",   name:"Turkmen",            native:"Türkmen",            flag:"🇹🇲", region:"Central Asian"},
  {code:"tg",   name:"Tajik",              native:"Тоҷикӣ",            flag:"🇹🇯", region:"Central Asian"},
  {code:"az",   name:"Azerbaijani",        native:"Azərbaycan",         flag:"🇦🇿", region:"Central Asian"},
  {code:"tt",   name:"Tatar",              native:"Татар",              flag:"🇷🇺", region:"Central Asian"},
  {code:"ba",   name:"Bashkir",            native:"Башҡортса",          flag:"🇷🇺", region:"Central Asian", wikiCode:"ba", gtFallback:"ru"},
  {code:"cv",   name:"Chuvash",            native:"Чӑвашла",            flag:"🇷🇺", region:"Central Asian", wikiCode:"cv", gtFallback:"ru"},
  {code:"ug",   name:"Uyghur",             native:"ئۇيغۇرچە",          flag:"🇨🇳", region:"Central Asian"},
  {code:"ps",   name:"Pashto",             native:"پښتو",               flag:"🇦🇫", region:"Central Asian"},
  {code:"ku",   name:"Kurdish (Kurmanji)", native:"Kurdî",              flag:"🌍",  region:"Central Asian"},
  {code:"ckb",  name:"Kurdish (Sorani)",   native:"کوردی",              flag:"🇮🇶", region:"Central Asian"},
  {code:"sah",  name:"Sakha (Yakut)",      native:"Саха тыла",          flag:"🇷🇺", region:"Central Asian", wikiCode:"sah", gtFallback:"ru"},
  {code:"os",   name:"Ossetian",           native:"Ирон",               flag:"🇷🇺", region:"Central Asian", wikiCode:"os", gtFallback:"ru"},
  {code:"tyv",  name:"Tuvan",              native:"Тыва дыл",           flag:"🇷🇺", region:"Central Asian", wikiCode:"tyv", gtFallback:"ru"},
  {code:"alt",  name:"Altai",              native:"Алтай тил",          flag:"🇷🇺", region:"Central Asian", wikiCode:"alt", gtFallback:"ru"},
  {code:"mhr",  name:"Mari (Eastern)",     native:"Олык марий",         flag:"🇷🇺", region:"Central Asian", wikiCode:"mhr", gtFallback:"ru"},
  {code:"mrj",  name:"Mari (Western)",     native:"Кырык мары",         flag:"🇷🇺", region:"Central Asian", wikiCode:"mrj", gtFallback:"ru"},
  {code:"udm",  name:"Udmurt",             native:"Удмурт",             flag:"🇷🇺", region:"Central Asian", wikiCode:"udm", gtFallback:"ru"},
  {code:"kv",   name:"Komi",               native:"Коми",               flag:"🇷🇺", region:"Central Asian", wikiCode:"kv", gtFallback:"ru"},
  {code:"myv",  name:"Erzya",              native:"Эрзянь",             flag:"🇷🇺", region:"Central Asian", wikiCode:"myv", gtFallback:"ru"},
  {code:"mdf",  name:"Moksha",             native:"Мокшень",            flag:"🇷🇺", region:"Central Asian", wikiCode:"mdf", gtFallback:"ru"},

  // ── EAST / SOUTHEAST ASIAN ────────────────────────────────────────────────
  {code:"ja",   name:"Japanese",           native:"日本語",              flag:"🇯🇵", region:"East Asian"},
  {code:"ko",   name:"Korean",             native:"한국어",              flag:"🇰🇷", region:"East Asian"},
  {code:"zh-CN",name:"Chinese (Simplified)",native:"中文简体",           flag:"🇨🇳", region:"East Asian"},
  {code:"zh-TW",name:"Chinese (Traditional)",native:"中文繁體",          flag:"🇹🇼", region:"East Asian"},
  {code:"mn",   name:"Mongolian",           native:"Монгол",            flag:"🇲🇳", region:"East Asian"},
  {code:"my",   name:"Burmese",             native:"မြန်မာဘာသာ",       flag:"🇲🇲", region:"SE Asian"},
  {code:"th",   name:"Thai",                native:"ภาษาไทย",          flag:"🇹🇭", region:"SE Asian"},
  {code:"lo",   name:"Lao",                 native:"ລາວ",               flag:"🇱🇦", region:"SE Asian"},
  {code:"km",   name:"Khmer",               native:"ខ្មែរ",             flag:"🇰🇭", region:"SE Asian"},
  {code:"vi",   name:"Vietnamese",          native:"Tiếng Việt",        flag:"🇻🇳", region:"SE Asian"},
  {code:"id",   name:"Indonesian",          native:"Bahasa Indonesia",  flag:"🇮🇩", region:"SE Asian"},
  {code:"ms",   name:"Malay",               native:"Bahasa Melayu",     flag:"🇲🇾", region:"SE Asian"},
  {code:"jv",   name:"Javanese",            native:"Basa Jawa",         flag:"🇮🇩", region:"SE Asian"},
  {code:"su",   name:"Sundanese",           native:"Basa Sunda",        flag:"🇮🇩", region:"SE Asian"},
  {code:"ceb",  name:"Cebuano",             native:"Cebuano",           flag:"🇵🇭", region:"SE Asian"},
  {code:"fil",  name:"Filipino (Tagalog)",  native:"Filipino",          flag:"🇵🇭", region:"SE Asian"},
  {code:"ilo",  name:"Ilokano",             native:"Ilokano",           flag:"🇵🇭", region:"SE Asian"},
  {code:"pam",  name:"Kapampangan",         native:"Kapampangan",       flag:"🇵🇭", region:"SE Asian", wikiCode:"pam", gtFallback:"fil"},
  {code:"tl",   name:"Tagalog",             native:"Tagalog",           flag:"🇵🇭", region:"SE Asian", wikiCode:"tl", gtFallback:"fil"},
  {code:"mi",   name:"Maori",               native:"Te Reo Māori",      flag:"🇳🇿", region:"SE Asian"},
  {code:"haw",  name:"Hawaiian",            native:"ʻŌlelo Hawaiʻi",    flag:"🇺🇸", region:"SE Asian"},

  // ── MIDDLE EAST / WEST ASIAN ──────────────────────────────────────────────
  {code:"ar",   name:"Arabic",              native:"العربية",           flag:"🇸🇦", region:"Middle East"},
  {code:"fa",   name:"Persian (Farsi)",     native:"فارسی",             flag:"🇮🇷", region:"Middle East"},
  {code:"iw",   name:"Hebrew",              native:"עברית",             flag:"🇮🇱", region:"Middle East"},
  {code:"hy",   name:"Armenian",            native:"Հայերեն",           flag:"🇦🇲", region:"Middle East"},
  {code:"ka",   name:"Georgian",            native:"ქართული",           flag:"🇬🇪", region:"Middle East"},
  {code:"dv",   name:"Dhivehi",             native:"ދިވެހި",             flag:"🇲🇻", region:"Middle East"},
  {code:"arc",  name:"Aramaic (Syriac)",    native:"ܐܪܡܝܐ",            flag:"🌍",  region:"Middle East", wikiCode:"arc", gtFallback:"ar"},
  {code:"azb",  name:"South Azerbaijani",   native:"تۆرکجه",            flag:"🇮🇷", region:"Middle East", wikiCode:"azb", gtFallback:"az"},
  {code:"glk",  name:"Gilaki",              native:"گیلکی",             flag:"🇮🇷", region:"Middle East", wikiCode:"glk", gtFallback:"fa"},
  {code:"mzn",  name:"Mazanderani",         native:"مازِرونی",          flag:"🇮🇷", region:"Middle East", wikiCode:"mzn", gtFallback:"fa"},
  {code:"lrc",  name:"Northern Luri",       native:"لۊری شومالی",       flag:"🇮🇷", region:"Middle East", wikiCode:"lrc", gtFallback:"fa"},

  // ── EUROPEAN ──────────────────────────────────────────────────────────────
  {code:"en",   name:"English",             native:"English",           flag:"🇬🇧", region:"European"},
  {code:"fr",   name:"French",              native:"Français",          flag:"🇫🇷", region:"European"},
  {code:"de",   name:"German",              native:"Deutsch",           flag:"🇩🇪", region:"European"},
  {code:"es",   name:"Spanish",             native:"Español",           flag:"🇪🇸", region:"European"},
  {code:"it",   name:"Italian",             native:"Italiano",          flag:"🇮🇹", region:"European"},
  {code:"pt",   name:"Portuguese",          native:"Português",         flag:"🇧🇷", region:"European"},
  {code:"ru",   name:"Russian",             native:"Русский",           flag:"🇷🇺", region:"European"},
  {code:"nl",   name:"Dutch",               native:"Nederlands",        flag:"🇳🇱", region:"European"},
  {code:"pl",   name:"Polish",              native:"Polski",            flag:"🇵🇱", region:"European"},
  {code:"uk",   name:"Ukrainian",           native:"Українська",        flag:"🇺🇦", region:"European"},
  {code:"sv",   name:"Swedish",             native:"Svenska",           flag:"🇸🇪", region:"European"},
  {code:"no",   name:"Norwegian",           native:"Norsk",             flag:"🇳🇴", region:"European"},
  {code:"da",   name:"Danish",              native:"Dansk",             flag:"🇩🇰", region:"European"},
  {code:"fi",   name:"Finnish",             native:"Suomi",             flag:"🇫🇮", region:"European"},
  {code:"el",   name:"Greek",               native:"Ελληνικά",          flag:"🇬🇷", region:"European"},
  {code:"cs",   name:"Czech",               native:"Čeština",           flag:"🇨🇿", region:"European"},
  {code:"sk",   name:"Slovak",              native:"Slovenčina",        flag:"🇸🇰", region:"European"},
  {code:"hu",   name:"Hungarian",           native:"Magyar",            flag:"🇭🇺", region:"European"},
  {code:"ro",   name:"Romanian",            native:"Română",            flag:"🇷🇴", region:"European"},
  {code:"bg",   name:"Bulgarian",           native:"Български",         flag:"🇧🇬", region:"European"},
  {code:"sr",   name:"Serbian",             native:"Српски",            flag:"🇷🇸", region:"European"},
  {code:"hr",   name:"Croatian",            native:"Hrvatski",          flag:"🇭🇷", region:"European"},
  {code:"bs",   name:"Bosnian",             native:"Bosanski",          flag:"🇧🇦", region:"European"},
  {code:"sl",   name:"Slovenian",           native:"Slovenščina",       flag:"🇸🇮", region:"European"},
  {code:"mk",   name:"Macedonian",          native:"Македонски",        flag:"🇲🇰", region:"European"},
  {code:"be",   name:"Belarusian",          native:"Беларуская",        flag:"🇧🇾", region:"European"},
  {code:"lt",   name:"Lithuanian",          native:"Lietuvių",          flag:"🇱🇹", region:"European"},
  {code:"lv",   name:"Latvian",             native:"Latviešu",          flag:"🇱🇻", region:"European"},
  {code:"et",   name:"Estonian",            native:"Eesti",             flag:"🇪🇪", region:"European"},
  {code:"is",   name:"Icelandic",           native:"Íslenska",          flag:"🇮🇸", region:"European"},
  {code:"ga",   name:"Irish",               native:"Gaeilge",           flag:"🇮🇪", region:"European"},
  {code:"cy",   name:"Welsh",               native:"Cymraeg",           flag:"🏴󠁧󠁢󠁷󠁬󠁳󠁿", region:"European"},
  {code:"eu",   name:"Basque",              native:"Euskara",           flag:"🇪🇸", region:"European"},
  {code:"ca",   name:"Catalan",             native:"Català",            flag:"🇪🇸", region:"European"},
  {code:"gl",   name:"Galician",            native:"Galego",            flag:"🇪🇸", region:"European"},
  {code:"af",   name:"Afrikaans",           native:"Afrikaans",         flag:"🇿🇦", region:"European"},
  {code:"sq",   name:"Albanian",            native:"Shqip",             flag:"🇦🇱", region:"European"},
  {code:"hy",   name:"Armenian",            native:"Հայերեն",           flag:"🇦🇲", region:"European"},
  {code:"az",   name:"Azerbaijani",         native:"Azərbaycan",        flag:"🇦🇿", region:"European"},
  {code:"tr",   name:"Turkish",             native:"Türkçe",            flag:"🇹🇷", region:"European"},
  {code:"la",   name:"Latin",               native:"Latina",            flag:"🏛️",  region:"European"},
  {code:"eo",   name:"Esperanto",           native:"Esperanto",         flag:"🌍",  region:"European"},
  {code:"ia",   name:"Interlingua",         native:"Interlingua",       flag:"🌍",  region:"European", wikiCode:"ia", gtFallback:"la"},
  {code:"io",   name:"Ido",                 native:"Ido",               flag:"🌍",  region:"European", wikiCode:"io", gtFallback:"eo"},
  {code:"vo",   name:"Volapük",             native:"Volapük",           flag:"🌍",  region:"European", wikiCode:"vo", gtFallback:"de"},
  {code:"jbo",  name:"Lojban",              native:"Lojban",            flag:"🌍",  region:"European", wikiCode:"jbo", gtFallback:"en"},
  {code:"mt",   name:"Maltese",             native:"Malti",             flag:"🇲🇹", region:"European"},
  {code:"lb",   name:"Luxembourgish",       native:"Lëtzebuergesch",    flag:"🇱🇺", region:"European"},
  {code:"fy",   name:"Frisian",             native:"Frysk",             flag:"🇳🇱", region:"European"},
  {code:"gd",   name:"Scots Gaelic",        native:"Gàidhlig",          flag:"🏴󠁧󠁢󠁳󠁣󠁴󠁿", region:"European"},
  {code:"sco",  name:"Scots",               native:"Scots",             flag:"🏴󠁧󠁢󠁳󠁣󠁴󠁿", region:"European", wikiCode:"sco", gtFallback:"en"},
  {code:"an",   name:"Aragonese",           native:"Aragonés",          flag:"🇪🇸", region:"European", wikiCode:"an", gtFallback:"es"},
  {code:"ast",  name:"Asturian",            native:"Asturianu",         flag:"🇪🇸", region:"European", wikiCode:"ast", gtFallback:"es"},
  {code:"ext",  name:"Extremaduran",        native:"Estremeñu",         flag:"🇪🇸", region:"European", wikiCode:"ext", gtFallback:"es"},
  {code:"oc",   name:"Occitan",             native:"Occitan",           flag:"🇫🇷", region:"European", wikiCode:"oc", gtFallback:"fr"},
  {code:"co",   name:"Corsican",            native:"Corsu",             flag:"🇫🇷", region:"European"},
  {code:"wa",   name:"Walloon",             native:"Walon",             flag:"🇧🇪", region:"European", wikiCode:"wa", gtFallback:"fr"},
  {code:"lij",  name:"Ligurian",            native:"Ligure",            flag:"🇮🇹", region:"European", wikiCode:"lij", gtFallback:"it"},
  {code:"vec",  name:"Venetian",            native:"Vèneto",            flag:"🇮🇹", region:"European", wikiCode:"vec", gtFallback:"it"},
  {code:"scn",  name:"Sicilian",            native:"Sicilianu",         flag:"🇮🇹", region:"European", wikiCode:"scn", gtFallback:"it"},
  {code:"nap",  name:"Neapolitan",          native:"Napulitano",        flag:"🇮🇹", region:"European", wikiCode:"nap", gtFallback:"it"},
  {code:"fur",  name:"Friulian",            native:"Furlan",            flag:"🇮🇹", region:"European", wikiCode:"fur", gtFallback:"it"},
  {code:"rm",   name:"Romansh",             native:"Rumantsch",         flag:"🇨🇭", region:"European", wikiCode:"rm", gtFallback:"de"},
  {code:"yi",   name:"Yiddish",             native:"ייִדיש",            flag:"🌍",  region:"European"},
  {code:"br",   name:"Breton",              native:"Brezhoneg",         flag:"🇫🇷", region:"European", wikiCode:"br", gtFallback:"fr"},
  {code:"kw",   name:"Cornish",             native:"Kernewek",          flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", region:"European", wikiCode:"kw", gtFallback:"en"},
  {code:"csb",  name:"Kashubian",           native:"Kaszëbsczi",        flag:"🇵🇱", region:"European", wikiCode:"csb", gtFallback:"pl"},
  {code:"szl",  name:"Silesian",            native:"Ślůnski",           flag:"🇵🇱", region:"European", wikiCode:"szl", gtFallback:"pl"},
  {code:"hsb",  name:"Upper Sorbian",       native:"Hornjoserbsce",     flag:"🇩🇪", region:"European", wikiCode:"hsb", gtFallback:"de"},
  {code:"dsb",  name:"Lower Sorbian",       native:"Dolnoserbski",      flag:"🇩🇪", region:"European", wikiCode:"dsb", gtFallback:"de"},
  {code:"pms",  name:"Piedmontese",         native:"Piemontèis",        flag:"🇮🇹", region:"European", wikiCode:"pms", gtFallback:"it"},
  {code:"frp",  name:"Arpitan",             native:"Arpetan",           flag:"🇫🇷", region:"European", wikiCode:"frp", gtFallback:"fr"},
  {code:"lmo",  name:"Lombard",             native:"Lombard",           flag:"🇮🇹", region:"European", wikiCode:"lmo", gtFallback:"it"},
  {code:"nds",  name:"Low German",          native:"Plattdüütsch",      flag:"🇩🇪", region:"European", wikiCode:"nds", gtFallback:"de"},
  {code:"bar",  name:"Bavarian",            native:"Boarisch",          flag:"🇩🇪", region:"European", wikiCode:"bar", gtFallback:"de"},
  {code:"als",  name:"Alemannic",           native:"Alemannisch",       flag:"🇨🇭", region:"European", wikiCode:"als", gtFallback:"de"},
  {code:"stq",  name:"Saterland Frisian",   native:"Seeltersk",         flag:"🇩🇪", region:"European", wikiCode:"stq", gtFallback:"de"},
  {code:"nn",   name:"Norwegian Nynorsk",   native:"Nynorsk",           flag:"🇳🇴", region:"European", wikiCode:"nn", gtFallback:"no"},
  {code:"nb",   name:"Norwegian Bokmål",    native:"Bokmål",            flag:"🇳🇴", region:"European", wikiCode:"nb", gtFallback:"no"},
  {code:"smn",  name:"Inari Sami",          native:"Anarâškielâ",       flag:"🇫🇮", region:"European", wikiCode:"smn", gtFallback:"fi"},
  {code:"se",   name:"Northern Sami",       native:"Sámegiella",        flag:"🇳🇴", region:"European", wikiCode:"se", gtFallback:"no"},
  {code:"hy",   name:"Armenian",            native:"Հայերեն",           flag:"🇦🇲", region:"European"},
  {code:"ka",   name:"Georgian",            native:"ქართული",           flag:"🇬🇪", region:"European"},
  {code:"ab",   name:"Abkhazian",           native:"Аҧсшәа",            flag:"🇬🇪", region:"European", wikiCode:"ab", gtFallback:"ru"},
  {code:"ce",   name:"Chechen",             native:"Нохчийн",           flag:"🇷🇺", region:"European", wikiCode:"ce", gtFallback:"ru"},
  {code:"av",   name:"Avar",                native:"Авар",              flag:"🇷🇺", region:"European", wikiCode:"av", gtFallback:"ru"},
  {code:"inh",  name:"Ingush",              native:"ГӀалгӀай",          flag:"🇷🇺", region:"European", wikiCode:"inh", gtFallback:"ru"},
  {code:"lez",  name:"Lezgian",             native:"Лезги",             flag:"🇷🇺", region:"European", wikiCode:"lez", gtFallback:"ru"},
  {code:"tab",  name:"Tabasaran",           native:"Табасаран",         flag:"🇷🇺", region:"European", wikiCode:"tab", gtFallback:"ru"},

  // ── AFRICAN ───────────────────────────────────────────────────────────────
  {code:"sw",   name:"Swahili",             native:"Kiswahili",         flag:"🇰🇪", region:"African"},
  {code:"am",   name:"Amharic",             native:"አማርኛ",             flag:"🇪🇹", region:"African"},
  {code:"ha",   name:"Hausa",               native:"Hausa",             flag:"🇳🇬", region:"African"},
  {code:"yo",   name:"Yoruba",              native:"Yorùbá",            flag:"🇳🇬", region:"African"},
  {code:"ig",   name:"Igbo",                native:"Igbo",              flag:"🇳🇬", region:"African"},
  {code:"zu",   name:"Zulu",                native:"isiZulu",           flag:"🇿🇦", region:"African"},
  {code:"xh",   name:"Xhosa",               native:"isiXhosa",          flag:"🇿🇦", region:"African"},
  {code:"af",   name:"Afrikaans",           native:"Afrikaans",         flag:"🇿🇦", region:"African"},
  {code:"so",   name:"Somali",              native:"Soomaali",          flag:"🇸🇴", region:"African"},
  {code:"st",   name:"Sesotho",             native:"Sesotho",           flag:"🇱🇸", region:"African"},
  {code:"sn",   name:"Shona",               native:"chiShona",          flag:"🇿🇼", region:"African"},
  {code:"rw",   name:"Kinyarwanda",         native:"Kinyarwanda",       flag:"🇷🇼", region:"African"},
  {code:"ny",   name:"Nyanja (Chichewa)",   native:"Chicheŵa",          flag:"🇲🇼", region:"African"},
  {code:"mg",   name:"Malagasy",            native:"Malagasy",          flag:"🇲🇬", region:"African"},
  {code:"ti",   name:"Tigrinya",            native:"ትግርኛ",              flag:"🇪🇷", region:"African"},
  {code:"lg",   name:"Luganda",             native:"Luganda",           flag:"🇺🇬", region:"African"},
  {code:"ln",   name:"Lingala",             native:"Lingála",           flag:"🇨🇩", region:"African"},
  {code:"ts",   name:"Tsonga",              native:"Xitsonga",          flag:"🇿🇦", region:"African"},
  {code:"nso",  name:"Sepedi (Northern Sotho)",native:"Sesotho sa Leboa",flag:"🇿🇦",region:"African"},
  {code:"tw",   name:"Twi (Akan)",          native:"Twi",               flag:"🇬🇭", region:"African"},
  {code:"ee",   name:"Ewe",                 native:"Eʋegbe",            flag:"🇬🇭", region:"African"},
  {code:"bm",   name:"Bambara",             native:"Bamanankan",        flag:"🇲🇱", region:"African"},
  {code:"om",   name:"Oromo",               native:"Afaan Oromoo",      flag:"🇪🇹", region:"African"},
  {code:"kri",  name:"Krio",                native:"Krio",              flag:"🇸🇱", region:"African"},
  {code:"wo",   name:"Wolof",               native:"Wolof",             flag:"🇸🇳", region:"African", wikiCode:"wo", gtFallback:"fr"},
  {code:"ff",   name:"Fula (Fulfulde)",     native:"Fulfulde",          flag:"🇳🇬", region:"African", wikiCode:"ff", gtFallback:"ha"},
  {code:"sg",   name:"Sango",               native:"Sängö",             flag:"🇨🇫", region:"African", wikiCode:"sg", gtFallback:"fr"},
  {code:"ln",   name:"Lingala",             native:"Lingála",           flag:"🇨🇩", region:"African"},
  {code:"kg",   name:"Kongo",               native:"Kikongo",           flag:"🇨🇩", region:"African", wikiCode:"kg", gtFallback:"fr"},
  {code:"ak",   name:"Akan",                native:"Akan",              flag:"🇬🇭", region:"African", wikiCode:"ak", gtFallback:"tw"},
  {code:"tn",   name:"Tswana",              native:"Setswana",          flag:"🇧🇼", region:"African", wikiCode:"tn", gtFallback:"st"},
  {code:"ss",   name:"Swati",               native:"siSwati",           flag:"🇸🇿", region:"African", wikiCode:"ss", gtFallback:"zu"},
  {code:"ve",   name:"Venda",               native:"Tshivenḓa",         flag:"🇿🇦", region:"African", wikiCode:"ve", gtFallback:"zu"},
  {code:"nr",   name:"South Ndebele",       native:"isiNdebele",        flag:"🇿🇦", region:"African", wikiCode:"nr", gtFallback:"zu"},
  {code:"nd",   name:"North Ndebele",       native:"isiNdebele",        flag:"🇿🇼", region:"African", wikiCode:"nd", gtFallback:"zu"},
  {code:"ki",   name:"Kikuyu",              native:"Gĩkũyũ",            flag:"🇰🇪", region:"African", wikiCode:"ki", gtFallback:"sw"},
  {code:"rn",   name:"Kirundi",             native:"Kirundi",           flag:"🇧🇮", region:"African", wikiCode:"rn", gtFallback:"rw"},
  {code:"dz",   name:"Dzongkha",            native:"རྫོང་ཁ",           flag:"🇧🇹", region:"African"},

  // ── AMERICAS / INDIGENOUS ─────────────────────────────────────────────────
  {code:"qu",   name:"Quechua",             native:"Runasimi",          flag:"🇵🇪", region:"Americas"},
  {code:"ay",   name:"Aymara",              native:"Aymar aru",         flag:"🇧🇴", region:"Americas"},
  {code:"gn",   name:"Guarani",             native:"Avañe'ẽ",           flag:"🇵🇾", region:"Americas"},
  {code:"ht",   name:"Haitian Creole",      native:"Kreyòl ayisyen",    flag:"🇭🇹", region:"Americas"},
  {code:"nah",  name:"Nahuatl",             native:"Nāhuatl",           flag:"🇲🇽", region:"Americas", wikiCode:"nah", gtFallback:"es"},
  {code:"myn",  name:"Mayan (Yucatec)",     native:"Maya",              flag:"🇲🇽", region:"Americas", wikiCode:"yua", gtFallback:"es"},

  // ── PACIFIC ───────────────────────────────────────────────────────────────
  {code:"sm",   name:"Samoan",              native:"Gagana fa'a Samoa", flag:"🇼🇸", region:"Pacific", wikiCode:"sm", gtFallback:"en"},
  {code:"to",   name:"Tongan",              native:"lea faka-Tonga",    flag:"🇹🇴", region:"Pacific", wikiCode:"to", gtFallback:"en"},
  {code:"fj",   name:"Fijian",              native:"Vosa Vakaviti",     flag:"🇫🇯", region:"Pacific", wikiCode:"fj", gtFallback:"en"},

  // ── CONSTRUCTED / OTHER ───────────────────────────────────────────────────
  {code:"eo",   name:"Esperanto",           native:"Esperanto",         flag:"🌍",  region:"Constructed"},
  {code:"la",   name:"Latin",               native:"Latina",            flag:"🏛️",  region:"Constructed"},
  {code:"yi",   name:"Yiddish",             native:"ייִדיש",            flag:"🌍",  region:"Constructed"},
  {code:"hmn",  name:"Hmong",               native:"Hmoob",             flag:"🇱🇦", region:"Other"},
  {code:"fy",   name:"Western Frisian",     native:"Frysk",             flag:"🇳🇱", region:"Other"},
];

// Deduplicate by code, keeping first occurrence
const seen = new Set();
const LANGUAGES = ALL_LANGUAGES.filter(l => {
  if (seen.has(l.code)) return false;
  seen.add(l.code); return true;
});

// Build lookup map by code and by Wikipedia subdomain
const LANG_BY_CODE = {};
const LANG_BY_WIKI = {};
LANGUAGES.forEach(l => {
  LANG_BY_CODE[l.code] = l;
  LANG_BY_WIKI[l.wikiCode || l.code] = l;
});

// Export
if (typeof module !== "undefined") module.exports = { LANGUAGES, LANG_BY_CODE, LANG_BY_WIKI };
